/** Right-click help copy for editor tools. */

export const TOOL_DESCRIPTIONS = {
  copy: "Copy the selected shapes, including group history, so they can be ungrouped after paste.",
  paste: "Paste shapes onto the workplane, keeping groups and nested history intact.",
  duplicate: "Create a copy of the selected shapes in place.",
  duplicateRepeat: "Duplicate the selection and keep repeating with the same offset.",
  delete: "Delete the selected shapes from the workplane.",
  undo: "Undo the last change.",
  redo: "Redo the last undone change.",
  group: "Combine selected shapes into one grouped object.",
  ungroup: "Ungroup the last Group only. Repeat to unwrap nested groups one level at a time.",
  intersect: "Keep only the overlapping volume of the selected shapes.",
  align: "Align selected shapes to each other along an axis.",
  mirror: "Mirror selected shapes across a chosen plane.",
  pattern: "Create a circular pattern of selected shapes around a pivot.",
  linearPattern: "Copy the selection along Width, Length, and/or Height. Hold spacing negative to go the other way. Applied patterns stay editable.",
  placementRuler: "Select a shape, then enter how far to move it in the X, Y, and Z fields. X/Y are on the workplane, Z is up.",
  snap: "Snap the selected shapes to the visible workplane grid.",
  chamfer: "Cut a flat bevel along selected edges. On a chamfered body, opens the last chamfer to edit.",
  fillet: "Round selected edges with a smooth radius. On a filleted body, opens the last fillet to edit.",
  hide: "Hide or show the selected shapes.",
  more: "Open extra tips and selection actions.",
  drop: "Drop the selection onto the workplane.",
  import: "Import STEP, STL, 3MF, or SVG. Optionally import as a hole.",
  export: "Export the current model to a downloadable file.",
  saveProject: "Overwrite the .peakcad file that matches this design name.",
  saveProjectAs: "Save this design as a new .peakcad file.",
  blueprint: "Export a printable 2D blueprint as PDF, DXF, and/or SVG.",
  settings: "Open workspace settings for units, grid, and appearance.",
  home: "Return to the home dashboard.",
  showControls: "Show the camera and measurement controls.",
  hideControls: "Hide the camera and measurement controls.",
  cameraHome: "Reset the camera to the default home view.",
  zoomIn: "Zoom the camera closer to the model.",
  zoomOut: "Zoom the camera farther from the model.",
  rulerTools: "Open measurement tools for distances on the model.",
  closeRulerTools: "Close the ruler tools and the active ruler mode.",
  addMeasurement: "Click points to add a length measurement. A ring appears when the line is a hole diameter; squares when it is square with the part.",
  moveMeasurement: "Drag existing measurement points to adjust them.",
  deleteMeasurement: "Click a measurement segment or point to remove it.",
  xray: "Cut through the model with an interior X-ray plane.",
  xrayToggle: "Turn the interior X-ray cutting plane on or off.",
  showObjects: "Show or hide the list of objects in the scene.",
  hideObjects: "Close the objects list.",
  geometryMode: "Switch to solid geometry editing.",
  sketchMode: "Switch to 2D sketch drawing tools.",
  // Sketch draw
  line: "Draw straight line segments between points.",
  bezier: "Draw a curved segment with editable control handles.",
  smooth: "Draw a smooth curve that flows through clicked points.",
  circle: "Click center, then drag to set the radius.",
  ellipse: "Click center, then drag to set width and height.",
  square: "Click and drag to place a square.",
  rect: "Click and drag to place a rectangle.",
  roundRect: "Click and drag to place a rectangle with rounded corners.",
  slot: "Click and drag to place an elongated slot profile.",
  triangle: "Click and drag to place a triangle.",
  polygon: "Click and drag to place a regular polygon. Use Sides to change count.",
  star: "Click and drag to place a star profile.",
  arc: "Place an arc by picking points along the curve.",
  offset: "Create an offset copy of a selected sketch profile.",
  select: "Select and move sketch points, segments, and images.",
  image: "Add a reference image onto the sketch plate.",
  refine: "Add or remove points on existing sketch curves.",
  erase: "Erase sketch points and segments.",
  measure: "Measure distances on the sketch plate.",
  extrude: "Extrude closed sketch profiles upward into 3D solids.",
  revolve: "Revolve a closed profile around a straight axis line.",
  cancelSketch: "Cancel the sketch and discard unfinished geometry.",
  // Shapes
  box: "Add a rectangular box solid.",
  cylinder: "Add a cylinder solid.",
  thread: "Add a metric thread solid.",
  sphere: "Add a sphere solid.",
  cone: "Add a cone solid.",
  pyramid: "Add a pyramid solid.",
  roof: "Add a triangular prism with adjustable side angles.",
  text: "Add extruded 3D text.",
  roundRoof: "Add a rounded roof solid.",
  halfSphere: "Add a half-sphere solid.",
  torus: "Add a torus (donut) solid.",
  tube: "Add a ring / tube solid.",
  shapePolygon: "Add a regular polygon prism.",
} as const;

export type ToolDescriptionKey = keyof typeof TOOL_DESCRIPTIONS;

export type ToolIndexCategory =
  | "Edit"
  | "Modify"
  | "File & project"
  | "View & measure"
  | "Modes"
  | "Sketch"
  | "Shapes";

export type ToolIndexEntry = {
  key: ToolDescriptionKey;
  label: string;
  category: ToolIndexCategory;
};

/** Ordered catalog for the Settings → Tools index. */
export const TOOL_INDEX: readonly ToolIndexEntry[] = [
  // Edit
  { key: "undo", label: "Undo", category: "Edit" },
  { key: "redo", label: "Redo", category: "Edit" },
  { key: "copy", label: "Copy", category: "Edit" },
  { key: "paste", label: "Paste", category: "Edit" },
  { key: "duplicate", label: "Duplicate", category: "Edit" },
  { key: "duplicateRepeat", label: "Duplicate and repeat", category: "Edit" },
  { key: "delete", label: "Delete", category: "Edit" },
  { key: "hide", label: "Hide / show", category: "Edit" },
  { key: "snap", label: "Snap to grid", category: "Edit" },
  { key: "drop", label: "Drop to workplane", category: "Edit" },
  { key: "more", label: "More", category: "Edit" },
  // Modify
  { key: "group", label: "Group", category: "Modify" },
  { key: "ungroup", label: "Ungroup", category: "Modify" },
  { key: "intersect", label: "Intersect", category: "Modify" },
  { key: "align", label: "Align", category: "Modify" },
  { key: "mirror", label: "Mirror", category: "Modify" },
  { key: "pattern", label: "Circular pattern", category: "Modify" },
  { key: "linearPattern", label: "Linear pattern", category: "Modify" },
  { key: "chamfer", label: "Chamfer", category: "Modify" },
  { key: "fillet", label: "Fillet", category: "Modify" },
  // File & project
  { key: "import", label: "Import", category: "File & project" },
  { key: "export", label: "Export", category: "File & project" },
  { key: "blueprint", label: "Blueprint", category: "File & project" },
  { key: "settings", label: "Settings", category: "File & project" },
  { key: "home", label: "Home", category: "File & project" },
  // View & measure
  { key: "showControls", label: "Show controls", category: "View & measure" },
  { key: "hideControls", label: "Hide controls", category: "View & measure" },
  { key: "cameraHome", label: "Camera home", category: "View & measure" },
  { key: "zoomIn", label: "Zoom in", category: "View & measure" },
  { key: "zoomOut", label: "Zoom out", category: "View & measure" },
  { key: "rulerTools", label: "Ruler tools", category: "View & measure" },
  { key: "addMeasurement", label: "Add measurement", category: "View & measure" },
  { key: "moveMeasurement", label: "Move measurement", category: "View & measure" },
  { key: "deleteMeasurement", label: "Delete measurement", category: "View & measure" },
  { key: "xray", label: "X-ray", category: "View & measure" },
  { key: "xrayToggle", label: "X-ray toggle", category: "View & measure" },
  { key: "showObjects", label: "Show objects", category: "View & measure" },
  { key: "hideObjects", label: "Hide objects", category: "View & measure" },
  // Modes
  { key: "geometryMode", label: "Geometry mode", category: "Modes" },
  { key: "sketchMode", label: "Sketch mode", category: "Modes" },
  // Sketch
  { key: "line", label: "Line", category: "Sketch" },
  { key: "bezier", label: "Bezier", category: "Sketch" },
  { key: "smooth", label: "Smooth", category: "Sketch" },
  { key: "circle", label: "Circle", category: "Sketch" },
  { key: "ellipse", label: "Ellipse", category: "Sketch" },
  { key: "square", label: "Square", category: "Sketch" },
  { key: "rect", label: "Rectangle", category: "Sketch" },
  { key: "roundRect", label: "Round rectangle", category: "Sketch" },
  { key: "slot", label: "Slot", category: "Sketch" },
  { key: "triangle", label: "Triangle", category: "Sketch" },
  { key: "polygon", label: "Polygon", category: "Sketch" },
  { key: "star", label: "Star", category: "Sketch" },
  { key: "arc", label: "Arc", category: "Sketch" },
  { key: "offset", label: "Offset", category: "Sketch" },
  { key: "select", label: "Select", category: "Sketch" },
  { key: "image", label: "Image", category: "Sketch" },
  { key: "refine", label: "Refine", category: "Sketch" },
  { key: "erase", label: "Erase", category: "Sketch" },
  { key: "measure", label: "Measure", category: "Sketch" },
  { key: "extrude", label: "Extrude", category: "Sketch" },
  { key: "revolve", label: "Revolve", category: "Sketch" },
  { key: "cancelSketch", label: "Cancel sketch", category: "Sketch" },
  // Shapes
  { key: "box", label: "Box", category: "Shapes" },
  { key: "cylinder", label: "Cylinder", category: "Shapes" },
  { key: "thread", label: "Thread", category: "Shapes" },
  { key: "sphere", label: "Sphere", category: "Shapes" },
  { key: "cone", label: "Cone", category: "Shapes" },
  { key: "pyramid", label: "Pyramid", category: "Shapes" },
  { key: "roof", label: "Triangle", category: "Shapes" },
  { key: "text", label: "Text", category: "Shapes" },
  { key: "roundRoof", label: "Round roof", category: "Shapes" },
  { key: "halfSphere", label: "Half sphere", category: "Shapes" },
  { key: "torus", label: "Torus", category: "Shapes" },
  { key: "tube", label: "Tube / ring", category: "Shapes" },
  { key: "shapePolygon", label: "Polygon solid", category: "Shapes" },
] as const;

export const TOOL_INDEX_CATEGORIES: readonly ToolIndexCategory[] = [
  "Edit",
  "Modify",
  "File & project",
  "View & measure",
  "Modes",
  "Sketch",
  "Shapes",
];
